####################
# INPUT
####################

stata_dta_inputs = \
	../input/tract_2010_characteristics_est.dta \
	../input/users_homeonlysample.dta \
	../input/users_est.dta \
	../input/choiceset_droploca.dta \
	../input/tract_pairs_2010_characteristics_est.dta \
	../input/choiceset_homeonly.dta \
	../input/choiceset_100.dta \
	../input/choiceset_50.dta \
	../input/choiceset_all.dta \
	../input/venues_est.dta \
	../input/trips_est.dta \
	../input/geoid11_dest.dta \
	../input/geoid11_home.dta \
	../input/geoid11_home_pair.dta \
	../input/geoid11_work_pair.dta \
	../input/geoid11_home_work.dta 

####################
# OUTPUT
####################

folders_and_symlinks=create_folders_and_symlinks.txt

####################
# dta files
####################

choicesets = \
	../output/choicesets/choiceset_whithisp_droploca.dta \
	../output/choicesets/choiceset_black_droploca.dta \
	../output/choicesets/choiceset_asian_droploca.dta \
	../output/choicesets/choiceset_whithisp_100.dta \
	../output/choicesets/choiceset_black_100.dta \
	../output/choicesets/choiceset_asian_100.dta \
	../output/choicesets/choiceset_whithisp_50.dta \
	../output/choicesets/choiceset_black_50.dta \
	../output/choicesets/choiceset_asian_50.dta \
	../output/choicesets/choiceset_whithisp.dta \
	../output/choicesets/choiceset_black.dta \
	../output/choicesets/choiceset_asian.dta 

estarrays_fastestmode = \
	../output/estarrays/fastestmode/estarray_whithisp_fastestmode.dta \
	../output/estarrays/fastestmode/estarray_black_fastestmode.dta \
	../output/estarrays/fastestmode/estarray_asian_fastestmode.dta \

estarrays_mintime= \
	../output/estarrays/mintime/estarray_whithisp.dta \
	../output/estarrays/mintime/estarray_black.dta \
	../output/estarrays/mintime/estarray_asian.dta \
	../output/estarrays/mintime/estarray_whithisp_spatialgender.dta \
	../output/estarrays/mintime/estarray_whithisp_spatialage.dta \
	../output/estarrays/mintime/estarray_whithisp_spatialincome.dta \
	../output/estarrays/mintime/estarray_black_spatialgender.dta \
	../output/estarrays/mintime/estarray_black_spatialage.dta \
	../output/estarrays/mintime/estarray_black_spatialincome.dta \
	../output/estarrays/mintime/estarray_asian_spatialgender.dta \
	../output/estarrays/mintime/estarray_asian_spatialage.dta \
	../output/estarrays/mintime/estarray_asian_spatialincome.dta \
	../output/estarrays/mintime/estarray_whithisp_locainfo2.dta \
	../output/estarrays/mintime/estarray_whithisp_locainfo1.dta \
	../output/estarrays/mintime/estarray_whithisp_droploca.dta \
	../output/estarrays/mintime/estarray_whithisp_carshare.dta \
	../output/estarrays/mintime/estarray_whithisp_revchain.dta \
	../output/estarrays/mintime/estarray_whithisp_fifth.dta \
	../output/estarrays/mintime/estarray_whithisp_half.dta \
	../output/estarrays/mintime/estarray_whithisp_lateadopt.dta \
	../output/estarrays/mintime/estarray_whithisp_disaggcuis.dta \
	../output/estarrays/mintime/estarray_whithisp_100.dta \
	../output/estarrays/mintime/estarray_whithisp_50.dta \
	../output/estarrays/mintime/estarray_whithisp_mainspec.dta \
	../output/estarrays/mintime/estarray_black_locainfo2.dta \
	../output/estarrays/mintime/estarray_black_locainfo1.dta \
	../output/estarrays/mintime/estarray_black_droploca.dta \
	../output/estarrays/mintime/estarray_black_carshare.dta \
	../output/estarrays/mintime/estarray_black_revchain.dta \
	../output/estarrays/mintime/estarray_black_fifth.dta \
	../output/estarrays/mintime/estarray_black_half.dta \
	../output/estarrays/mintime/estarray_black_lateadopt.dta \
	../output/estarrays/mintime/estarray_black_disaggcuis.dta \
	../output/estarrays/mintime/estarray_black_100.dta \
	../output/estarrays/mintime/estarray_black_50.dta \
	../output/estarrays/mintime/estarray_black_mainspec.dta \
	../output/estarrays/mintime/estarray_asian_locainfo2.dta \
	../output/estarrays/mintime/estarray_asian_locainfo1.dta \
	../output/estarrays/mintime/estarray_asian_droploca.dta \
	../output/estarrays/mintime/estarray_asian_carshare.dta \
	../output/estarrays/mintime/estarray_asian_revchain.dta \
	../output/estarrays/mintime/estarray_asian_fifth.dta \
	../output/estarrays/mintime/estarray_asian_half.dta \
	../output/estarrays/mintime/estarray_asian_lateadopt.dta \
	../output/estarrays/mintime/estarray_asian_disaggcuis.dta \
	../output/estarrays/mintime/estarray_asian_100.dta \
	../output/estarrays/mintime/estarray_asian_50.dta \
	../output/estarrays/mintime/estarray_asian_mainspec.dta 

estarrays_norg= \
	../output/estarrays/norg/estarray_whithisp_homeonly.dta \
	../output/estarrays/norg/estarray_black_homeonly.dta \
	../output/estarrays/norg/estarray_asian_homeonly.dta \
	../output/estarrays/norg/estarray_whithisp_homeonlysample.dta \
	../output/estarrays/norg/estarray_black_homeonlysample.dta \
	../output/estarrays/norg/estarray_asian_homeonlysample.dta 

estarrays_sixom=\
	../output/estarrays/sixom/estarray_asian_100.dta \
	../output/estarrays/sixom/estarray_asian_50.dta \
	../output/estarrays/sixom/estarray_asian_carshare.dta \
	../output/estarrays/sixom/estarray_asian_disaggcuis.dta \
	../output/estarrays/sixom/estarray_asian_droploca.dta \
	../output/estarrays/sixom/estarray_asian.dta \
	../output/estarrays/sixom/estarray_asian_fifth.dta \
	../output/estarrays/sixom/estarray_asian_genderspecific.dta \
	../output/estarrays/sixom/estarray_asian_half.dta \
	../output/estarrays/sixom/estarray_asian_lateadopt.dta \
	../output/estarrays/sixom/estarray_asian_locainfo1.dta \
	../output/estarrays/sixom/estarray_asian_locainfo2.dta \
	../output/estarrays/sixom/estarray_asian_mainspec.dta \
	../output/estarrays/sixom/estarray_asian_revchain.dta \
	../output/estarrays/sixom/estarray_asian_spatialage.dta \
	../output/estarrays/sixom/estarray_asian_spatial.dta \
	../output/estarrays/sixom/estarray_asian_spatialgender.dta \
	../output/estarrays/sixom/estarray_asian_spatialincome.dta \
	../output/estarrays/sixom/estarray_black_100.dta \
	../output/estarrays/sixom/estarray_black_50.dta \
	../output/estarrays/sixom/estarray_black_carshare.dta \
	../output/estarrays/sixom/estarray_black_disaggcuis.dta \
	../output/estarrays/sixom/estarray_black_droploca.dta \
	../output/estarrays/sixom/estarray_black.dta \
	../output/estarrays/sixom/estarray_black_fifth.dta \
	../output/estarrays/sixom/estarray_black_genderspecific.dta \
	../output/estarrays/sixom/estarray_black_half.dta \
	../output/estarrays/sixom/estarray_black_lateadopt.dta \
	../output/estarrays/sixom/estarray_black_locainfo1.dta \
	../output/estarrays/sixom/estarray_black_locainfo2.dta \
	../output/estarrays/sixom/estarray_black_mainspec.dta \
	../output/estarrays/sixom/estarray_black_revchain.dta \
	../output/estarrays/sixom/estarray_black_spatialage.dta \
	../output/estarrays/sixom/estarray_black_spatial.dta \
	../output/estarrays/sixom/estarray_black_spatialgender.dta \
	../output/estarrays/sixom/estarray_black_spatialincome.dta \
	../output/estarrays/sixom/estarray_raceblind.dta \
	../output/estarrays/sixom/estarray_whithisp_100.dta \
	../output/estarrays/sixom/estarray_whithisp_50.dta \
	../output/estarrays/sixom/estarray_whithisp_carshare.dta \
	../output/estarrays/sixom/estarray_whithisp_disaggcuis.dta \
	../output/estarrays/sixom/estarray_whithisp_droploca.dta \
	../output/estarrays/sixom/estarray_whithisp.dta \
	../output/estarrays/sixom/estarray_whithisp_fifth.dta \
	../output/estarrays/sixom/estarray_whithisp_genderspecific.dta \
	../output/estarrays/sixom/estarray_whithisp_half.dta \
	../output/estarrays/sixom/estarray_whithisp_lateadopt.dta \
	../output/estarrays/sixom/estarray_whithisp_locainfo1.dta \
	../output/estarrays/sixom/estarray_whithisp_locainfo2.dta \
	../output/estarrays/sixom/estarray_whithisp_mainspec.dta \
	../output/estarrays/sixom/estarray_whithisp_revchain.dta \
	../output/estarrays/sixom/estarray_whithisp_spatialage.dta \
	../output/estarrays/sixom/estarray_whithisp_spatial.dta \
	../output/estarrays/sixom/estarray_whithisp_spatialgender.dta \
	../output/estarrays/sixom/estarray_whithisp_spatialincome.dta 

output_all=$(choicesets)
output_all+=$(estarrays_fastestmode)
output_all+=$(estarrays_mintime)
output_all+=$(estarrays_norg)
output_all+=$(estarrays_sixom)

#####################
# Work section
#####################

all: $(folders_and_symlinks) $(output_all)

$(folders_and_symlinks): create_folders_and_symlinks.sh
	-bash 	create_folders_and_symlinks.sh
	echo "">create_folders_and_symlinks.txt

$(output_all): $(stata_dta_inputs) DATA_PREP_estarray_program.do estarrays_DTAs.do run.sbatch
	sbatch -W run.sbatch

edit_sbatch: edit_sbatch.sh
	-bash edit_sbatch.sh
