#####################
# OUTPUT
#####################

distribute_functions=distribute_commonfunctions.txt

#####################
# Work section
#####################

all: $(distribute_functions) 

$(distribute_functions): distribute_commonfunctions.sh
	-bash distribute_commonfunctions.sh
	@echo ""> distribute_commonfunctions.txt


