###################
# Programmes
###################

PROGS = dissimilarity_tables_functions.jl

####################
# INPUT
####################

####################
# Dissimilarities
####################

dissim_residential =\
	../input/dissimilarity_index_pairwise_residential.csv \
	../input/dissimilarity_index_residential.csv \

dissim_sixom_mainspec=\
	../input/sixom/dissimilarity_index_venue_level_sixom_mainspec.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_mainspec.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_mainspec.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_mainspec.csv \

dissim_sixom_robustnesschecks=\
	../input/sixom/dissimilarity_index_venue_level_sixom_lateadopt.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_half.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_fifth.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_droploca.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_locainfo1.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_locainfo2.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_carshare.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_revchain.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_disaggcuis.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_50.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_100.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_lateadopt.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_half.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_fifth.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_droploca.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_locainfo1.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_locainfo2.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_carshare.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_revchain.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_disaggcuis.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_50.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_100.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_lateadopt.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_half.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_fifth.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_droploca.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_locainfo1.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_locainfo2.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_carshare.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_revchain.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_disaggcuis.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_50.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_100.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_lateadopt.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_half.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_fifth.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_droploca.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_locainfo1.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_locainfo2.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_carshare.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_revchain.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_disaggcuis.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_50.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_100.csv \

dissim_sixom_nlogit=\
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_nlogit_nested2.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_nlogit_nested2.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_nlogit_nested2.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_nlogit_nested2.csv \
	../input/sixom/dissimilarity_index_pairwise_tract_level_sixom_nlogit_nested1.csv \
	../input/sixom/dissimilarity_index_tract_level_sixom_nlogit_nested1.csv \
	../input/sixom/dissimilarity_index_pairwise_venue_level_sixom_nlogit_nested1.csv \
	../input/sixom/dissimilarity_index_venue_level_sixom_nlogit_nested1.csv 

#####################
# OUTPUT
#####################

folders_and_symlinks=create_folders_and_symlinks.txt

folders_and_symlinks_quick_version=create_folders_and_symlinks_quick_version.txt

#########
# Tex
#########

Tex_robustnesschecks=\
	../output/sixom/dissimilarity_robustnesschecks_venue_level_comp_within_race.tex \
	../output/sixom/dissimilarity_robustnesschecks_tract_level_comp_within_race.tex \
	../output/sixom/dissimilarity_robustnesschecks_venue_level_comp_across_race.tex \
	../output/sixom/dissimilarity_robustnesschecks_tract_level_comp_across_race.tex

Tex_mainspec=\
	../output/sixom/dissimilarity_mainspec_venue_level.tex \
	../output/sixom/dissimilarity_mainspec_tract_level.tex 

Tex_homeonly=\
	../output/sixom/dissimilarity_mainspec_venue_level_homeonly.tex \
	../output/sixom/dissimilarity_mainspec_tract_level_homeonly.tex 

#####################
# Work section
#####################

all: $(folders_and_symlinks) $(Tex_robustnesschecks) $(Tex_mainspec) $(Tex_homeonly)

all_quick_version: $(folders_and_symlinks_quick_version) $(Tex_mainspec)

$(folders_and_symlinks): create_folders_and_symlinks.sh
	-bash 	create_folders_and_symlinks.sh
	@echo "">create_folders_and_symlinks.txt

$(folders_and_symlinks_quick_version): create_folders_and_symlinks.sh
	-bash 	create_folders_and_symlinks.sh
	@echo "">create_folders_and_symlinks_quick_version.txt
	
$(Tex_robustnesschecks): $(PROGS) $(dissim_residential) $(dissim_sixom_mainspec) $(dissim_sixom_robustnesschecks) $(dissim_sixom_nlogit) dissimilarity_tables_robustnesschecks.jl dissimilarity_tables_robustnesschecks.sbatch
	sbatch -W dissimilarity_tables_robustnesschecks.sbatch	

$(Tex_mainspec): $(PROGS) $(dissim_residential) $(dissim_sixom_mainspec) dissimilarity_tables_mainspec.jl dissimilarity_tables_mainspec.sbatch
	sbatch -W dissimilarity_tables_mainspec.sbatch

$(Tex_homeonly): $(PROGS) $(dissim_residential) $(dissim_sixom_mainspec) dissimilarity_tables_homeonly.jl dissimilarity_tables_homeonly.sbatch
	sbatch -W dissimilarity_tables_homeonly.sbatch

edit_sbatch: edit_sbatch.sh
	-bash edit_sbatch.sh

